#!/bin/sh

bat="/sys/class/power_supply/BAT1/"
per="$(cat "$bat/capacity")"
icon=""
status="$(cat "$bat/status")"

icon() {
    if [ "$status" = "Full" ]; then
        icon="󰂄"
    elif [ "$status" = "Charging" ];then

        if [ "$per" -gt "90" ]; then
            icon="󰂅"
        elif [ "$per" -gt "80" ]; then
            icon="󰂋"
        elif [ "$per" -gt "70" ]; then
            icon="󰂊"
        elif [ "$per" -gt "60" ]; then
            icon="󰢞"
        elif [ "$per" -gt "50" ]; then
            icon="󰂉"
        elif [ "$per" -gt "40" ]; then
            icon="󰢝"
        elif [ "$per" -gt "30" ]; then
            icon="󰂈"
        elif [ "$per" -gt "20" ]; then
            icon="󰂇"
        elif [ "$per" -gt "10" ]; then
            icon="󰂆"
            notify-send -u critical "Battery Low" "Connect Charger"
        else
            icon="󰢜"
            notify-send -u critical "Battery Low" "Connect Charger"
        fi

    else
            
        if [ "$per" -gt "90" ]; then
            icon="󰁹"
        elif [ "$per" -gt "80" ]; then
            icon="󰂂"
        elif [ "$per" -gt "70" ]; then
            icon="󰂁"
        elif [ "$per" -gt "60" ]; then
            icon="󰂀"
        elif [ "$per" -gt "50" ]; then
            icon="󰁿"
        elif [ "$per" -gt "40" ]; then
            icon="󰁾"
        elif [ "$per" -gt "30" ]; then
            icon="󰁽"
        elif [ "$per" -gt "20" ]; then
            icon="󰁼"
        elif [ "$per" -gt "10" ]; then
            icon="󰁼"
            notify-send -u critical "Battery Low" "Connect Charger"
        elif [ "$per" -gt "0" ]; then
            icon="󰁻"
            notify-send -u critical "Battery Low" "Connect Charger"
        else
            echo 󰂎 && exit
        fi
    fi
echo "$icon"
}

percent() {
echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
exit
