#!/usr/bin/env dash

# nmcli -f NAME,TYPE,DEVICE connection show --active 
WIRELESS_DEV="wlp3s0"
ETHERNET_DEV="enp4s0f1"

ETH="$(ip -o link show | rg "${ETHERNET_DEV}.*state UP")"
WIFI="$(ip -o link show | rg "${WIRELESS_DEV}.*state UP"  )"

if [ ! -z "$ETH" ]; then
    echo "󰈀"
elif [ ! -z "$WIFI" ]; then

    SIGNAL_STRENGTH=$(iw dev $WIRELESS_DEV link | rg "signal" | cut -d: -f2 | sed 's/ dBm//' )
    WIFI_SSID=$(iw dev $WIRELESS_DEV link | rg "SSID" | cut -d: -f2)

    # echo "Connected to WiFi: $WIFI_SSID"

    if [ "$SIGNAL_STRENGTH" -ge -50 ]; then
        echo "󰤨"  # Signal Icon (Strong)
    elif [ "$SIGNAL_STRENGTH" -ge -70 ]; then
        echo "󰤥"  # Signal Icon (Medium)
    elif [ "$SIGNAL_STRENGTH" -ge -90 ]; then
        echo "󰤢"  # Signal Icon (Weak)
    else
        echo "󰤟"  # Signal Icon (Very Weak)
    fi

else
    echo "󰖪"
fi
